/*
* This code is generated by shch-maven-plugin.
*
*/
package ${basePackage}.controller;

import com.edward.io.base.controller.BaseController;
import ${basePackage}.service.${domain}Service;
import org.springframework.util.Assert;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RestController;

/**
* Created by ${author} on ${date}.
*/
@RestController
@RequestMapping("/api/${domain}")
public class ${domain}Controller extends BaseController<${domain}Service, ${domain}ControllerBean> {

    @Autowired
    private ${domain}Service ${domain?uncap_first}Service;

    @Override
    protected void validateRequest(${domain}ControllerBean request) {
        Assert.notNull(request, "lacks of request body");
    }
}
