/*
* This code is generated by shch-maven-plugin.
*
*/
package ${basePackage}.dao;

import com.edward.io.base.dao.DaoAdapter;
import ${basePackage}.domain.${domain};
import ${basePackage}.domain.${domain}Key;
import org.springframework.stereotype.Component;

/**
* Created by ${author} on ${date}.
*/
@Component
public class ${domain}Dao extends DaoAdapter<${domain},${domain}Key> {

}
