/*
* This code is generated by shch-maven-plugin.
*
*/
package com.edward.io.demo.dao;

import com.edward.io.base.dao.DaoAdapter;
import com.edward.io.demo.domain.WpPosts;
import com.edward.io.demo.domain.WpPostsKey;
import org.springframework.stereotype.Component;

/**
* Created by edwardcheng on 2017/09/10.
*/
@Component
public class WpPostsDao extends DaoAdapter<WpPosts,WpPostsKey> {

}
