/*
* This code is generated by shch-maven-plugin.
*
*/
package com.edward.io.demo.dao;

import com.edward.io.base.dao.DaoAdapter;
import com.edward.io.demo.domain.WpUsers;
import com.edward.io.demo.domain.WpUsersKey;
import org.springframework.stereotype.Component;

/**
* Created by edwardcheng on 2017/09/10.
*/
@Component
public class WpUsersDao extends DaoAdapter<WpUsers,WpUsersKey> {

}
