/*
* This code is generated by shch-maven-plugin.
*
*/
package com.edward.io.demo.controller;

import com.edward.io.base.controller.BaseController;
import com.edward.io.demo.service.WpPostsService;
import org.springframework.util.Assert;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RestController;

/**
* Created by edwardcheng on 2017/09/10.
*/
@RestController
@RequestMapping("/api/WpPosts")
public class WpPostsController extends BaseController<WpPostsService, WpPostsControllerBean> {

    @Autowired
    private WpPostsService wpPostsService;

    @Override
    protected void validateRequest(WpPostsControllerBean request) {
        Assert.notNull(request, "lacks of request body");
    }
}
