/*
* This code is generated by shch-maven-plugin.
*
*/
package com.edward.io.demo.controller;

import com.edward.io.base.controller.ControllerBean;
import com.edward.io.demo.domain.WpUsersKey;
import com.edward.io.demo.dto.WpUsersDto;

import java.io.Serializable;

/**
* Created by edwardcheng on 2017/09/10.
*/
public class WpUsersControllerBean extends ControllerBean<WpUsersDto> {

    @Override
    public WpUsersDto transform() {
        WpUsersDto dto = new WpUsersDto();
        //you can write code here for transfering from request object to dto
        return dto;
    }

    @Override
    public Serializable getPrimaryKey() {
        WpUsersKey key = new WpUsersKey();
        //you can write code here for transfering from request object domain key
        return key;
    }

    @Override
    public String getEntityName() {
        return "WpUsers";
    }
}
