/*
* This code is generated by shch-maven-plugin.
*
*/
package com.edward.io.demo.controller;

import com.edward.io.base.controller.BaseController;
import com.edward.io.demo.service.WpUsersService;
import org.springframework.util.Assert;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RestController;

/**
* Created by edwardcheng on 2017/09/10.
*/
@RestController
@RequestMapping("/api/WpUsers")
public class WpUsersController extends BaseController<WpUsersService, WpUsersControllerBean> {

    @Autowired
    private WpUsersService wpUsersService;

    @Override
    protected void validateRequest(WpUsersControllerBean request) {
        Assert.notNull(request, "lacks of request body");
    }
}
