/*
* This code is generated by shch-maven-plugin.
*
*/
package com.edward.io.demo.dto;

import com.edward.io.base.dto.BaseDto;
import com.edward.io.demo.domain.WpUsers;

/**
* Created by edwardcheng on 2017/09/10.
*/
public class WpUsersDto implements BaseDto<WpUsers> {

    public WpUsers transform() {
        WpUsers entity = new WpUsers();
        //you can write code here for transfering from dto to domain
        return entity;
    }
}
