/*
* This code is generated by shch-maven-plugin.
*
*/
package com.edward.io.demo.service;

import com.edward.io.base.service.BaseService;
import com.edward.io.demo.domain.WpPosts;
import com.edward.io.demo.domain.WpPostsKey;
import com.edward.io.demo.dto.WpPostsDto;
import com.edward.io.demo.mapper.WpPostsMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Created by edwardcheng on 2017/09/10.
*/
@Component
public class WpPostsService extends BaseService<WpPosts,WpPostsKey,WpPostsDto> {

    @Autowired
    private WpPostsMapper wpPostsMapper;

    @Override
    protected WpPostsDto transform(WpPosts entity) {
        WpPostsDto dto = new WpPostsDto();
        //you can write code here for transfering from entity to dto
        return dto;
    }
}
