/*
* This code is generated by shch-maven-plugin.
*
*/
package com.edward.io.demo.service;

import com.edward.io.base.service.BaseService;
import com.edward.io.demo.domain.WpUsers;
import com.edward.io.demo.domain.WpUsersKey;
import com.edward.io.demo.dto.WpUsersDto;
import com.edward.io.demo.mapper.WpUsersMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Created by edwardcheng on 2017/09/10.
*/
@Component
public class WpUsersService extends BaseService<WpUsers,WpUsersKey,WpUsersDto> {

    @Autowired
    private WpUsersMapper wpUsersMapper;

    @Override
    protected WpUsersDto transform(WpUsers entity) {
        WpUsersDto dto = new WpUsersDto();
        //you can write code here for transfering from entity to dto
        return dto;
    }
}
